from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from drf_spectacular.utils import extend_schema

from Api.serializers.admin.adminPreRegistrationSerializer import (
    AdminPreRegistrationStartSerializer,
    AdminPreRegistrationConfirmSerializer,
    AdminPreRegistrationStartResponseSerializer,
    AdminPreRegistrationConfirmResponseSerializer
)
from Controllers.actions.admin.adminPreRegistrationActions import AdminPreRegistrationActions

class AdminPreRegistrationViewSet(viewsets.ViewSet):
    """
    API viewset for administrator user cryptographic pre-registration flow.
    
    All requests and responses pass through SEDecryptMiddleware,
    using the Desktop hardware key (VotaAI_SecureKey_1) in TPM.
    """
    permission_classes = [AllowAny]

    @extend_schema(
        summary="Start admin user pre-registration",
        description=(
            "Receives email, password and physical machine public key. "
            "Creates pending user, links machine, generates TOTP secret and provisioning URI. "
            "Returns response signed with server TPM and encrypted for machine public key."
        ),
        request=AdminPreRegistrationStartSerializer,
        responses={
            200: AdminPreRegistrationStartResponseSerializer,
            400: {"type": "object", "properties": {"error": {"type": "string"}}}
        },
        tags=["Admin Pre-Registration"],
        auth=[]
    )
    def create(self, request):
        """
        POST /api/admin/pre-registration/
        Shortcut to initiate pre-registration.
        """
        return self._start(request)

    @extend_schema(
        summary="Start admin user pre-registration (explicit route)",
        description="Alternative endpoint identical to POST /api/admin/pre-registration/.",
        request=AdminPreRegistrationStartSerializer,
        responses={
            200: AdminPreRegistrationStartResponseSerializer,
            400: {"type": "object", "properties": {"error": {"type": "string"}}}
        },
        tags=["Admin Pre-Registration"],
        auth=[]
    )
    @action(detail=False, methods=['post'], url_path='start')
    def start(self, request):
        """
        POST /api/admin/pre-registration/start/
        """
        return self._start(request)

    def _start(self, request):
        serializer = AdminPreRegistrationStartSerializer(
            data=request.data,
            context={'request': request}
        )
        serializer.is_valid(raise_exception=True)

        client_pub_key_fallback = getattr(request, '_client_public_key', None)
        result = AdminPreRegistrationActions.startPreRegistration(
            serializer.validated_data,
            client_pub_key_fallback=client_pub_key_fallback
        )
        return Response(result, status=status.HTTP_200_OK)

    @extend_schema(
        summary="Confirm admin user pre-registration with TOTP",
        description=(
            "Receives email, totp_code and digital signature generated by physical machine private key. "
            "Validates signature with machine public key, validates TOTP code, activates user "
            "and assigns Administrator role."
        ),
        request=AdminPreRegistrationConfirmSerializer,
        responses={
            200: AdminPreRegistrationConfirmResponseSerializer,
            400: {"type": "object", "properties": {"error": {"type": "string"}}}
        },
        tags=["Admin Pre-Registration"],
        auth=[]
    )
    @action(detail=False, methods=['post'], url_path='confirm')
    def confirm(self, request):
        """
        POST /api/admin/pre-registration/confirm/
        """
        serializer = AdminPreRegistrationConfirmSerializer(
            data=request.data,
            context={'request': request}
        )
        serializer.is_valid(raise_exception=True)

        result = AdminPreRegistrationActions.confirmPreRegistration(
            serializer.validated_data,
            raw_data=request.data
        )
        return Response(result, status=status.HTTP_200_OK)
