# Generated by Django 5.2 on 2026-09-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chave_publica_maquina',
            field=models.TextField(blank=True, help_text='Chave pública RSA da máquina atrelada ao usuário para validação de hardware e criptografia', null=True, verbose_name='chave pública da máquina'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Segredo Base32 para autenticação em dois fatores (TOTP)', max_length=64, null=True, verbose_name='segredo TOTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='last name'),
        ),
    ]
