# Generated by Django 5.2 on 2026-09-16 12:10

import Domain.models.proxies.election.electionProxy
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0002_user_chave_publica_maquina_user_totp_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last modified.', verbose_name='Updated At')),
                ('title', models.CharField(help_text='Title of the election', max_length=255, verbose_name='title')),
                ('public_key', models.TextField(help_text='Election public key for encrypting ballots', verbose_name='public key')),
                ('start_datetime', models.DateTimeField(blank=True, help_text='Voting start date and time', null=True, verbose_name='start date and time')),
                ('end_datetime', models.DateTimeField(blank=True, help_text='Voting end date and time', null=True, verbose_name='end date and time')),
                ('key_handle', models.CharField(help_text='Hardware key handle in the machine TPM/SE', max_length=255, verbose_name='key handle')),
                ('machine_signature', models.TextField(blank=True, default='', help_text='Digital signature produced by the desktop machine', verbose_name='machine signature')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('CLOSED', 'Closed'), ('TALLIED', 'Tallied')], default='CREATED', max_length=30, verbose_name='status')),
                ('ballot_snapshot', models.JSONField(blank=True, null=True, verbose_name='ballot snapshot')),
                ('electoral_college_snapshot', models.JSONField(blank=True, null=True, verbose_name='electoral college snapshot')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'ordering': ['-created_at'],
            },
            bases=(Domain.models.proxies.election.electionProxy.ElectionProxy, models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last modified.', verbose_name='Updated At')),
                ('question', models.TextField(help_text='Question text or ballot statement', verbose_name='question')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order of the question on the ballot', verbose_name='order')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Domain.election', verbose_name='election')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last modified.', verbose_name='Updated At')),
                ('label', models.CharField(help_text='Label or text of the voting option', max_length=255, verbose_name='label')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Domain.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last modified.', verbose_name='Updated At')),
                ('tally_hash', models.CharField(help_text='Cryptographic audit hash verifying the tally computation', max_length=255, verbose_name='tally hash')),
                ('tally_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the tally was performed', verbose_name='tally date and time')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tallies', to='Domain.election', verbose_name='election')),
            ],
            options={
                'verbose_name': 'Tally',
                'verbose_name_plural': 'Tallies',
                'ordering': ['-tally_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last modified.', verbose_name='Updated At')),
                ('id_generated', models.CharField(help_text='Unique identifier or receipt hash for the vote', max_length=255, unique=True, verbose_name='generated ID / receipt hash')),
                ('content', models.TextField(help_text='Encrypted payload of the vote cast by the voter', verbose_name='encrypted content')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='Domain.election', verbose_name='election')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last modified.', verbose_name='Updated At')),
                ('full_name', models.CharField(help_text='Full name of the voter', max_length=255, verbose_name='full name')),
                ('email', models.EmailField(help_text='Email of the voter', max_length=254, verbose_name='email')),
                ('nickname', models.CharField(blank=True, default='', help_text='Nickname or display name', max_length=150, verbose_name='nickname')),
                ('password', models.CharField(blank=True, default='', help_text='Password or hashed token for the voter', max_length=255, verbose_name='password')),
                ('has_voted', models.BooleanField(default=False, help_text='Indicates whether this voter has already cast their ballot', verbose_name='has voted')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_college', to='Domain.election', verbose_name='election')),
            ],
            options={
                'verbose_name': 'Electoral College Voter',
                'verbose_name_plural': 'Electoral College',
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(fields=('election', 'email'), name='unique_voter_per_election')],
            },
        ),
    ]
