# Generated by Django 5.2 on 2026-09-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0003_election_question_option_tally_vote_electoralcollege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='ballot_snapshot',
        ),
        migrations.RemoveField(
            model_name='election',
            name='electoral_college_snapshot',
        ),
    ]
