# Generated by Django 5.2 on 2026-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0004_remove_election_ballot_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['label'], 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterField(
            model_name='electoralcollege',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Hashed password of the voter (never stored in plaintext)', max_length=255, verbose_name='password hash'),
        ),
    ]
