# Generated by Django 5.2 on 2026-09-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0005_alter_option_options_alter_electoralcollege_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electoralcollege',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='First name of the voter extracted from full name', max_length=150, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='id_generated',
            field=models.CharField(help_text='Unique identifier for the vote', max_length=255, unique=True, verbose_name='generated ID'),
        ),
    ]
