# Generated by Django 5.2 on 2026-09-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0006_alter_electoralcollege_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usuario_maquina',
            field=models.CharField(blank=True, db_index=True, help_text='Identificador único e agnóstico de SO do dispositivo/máquina física', max_length=64, null=True, verbose_name='usuário de máquina'),
        ),
    ]
