# Generated by Django 5.2 on 2026-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0007_user_usuario_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chave_publica_maquina',
            field=models.TextField(blank=True, help_text='Machine RSA public key linked to the user for hardware validation and cryptography', null=True, verbose_name='machine public key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32 secret for two-factor authentication (TOTP)', max_length=64, null=True, verbose_name='TOTP secret'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario_maquina',
            field=models.CharField(blank=True, db_index=True, help_text='Unique, OS-agnostic identifier of the physical device or machine', max_length=64, null=True, verbose_name='machine user'),
        ),
    ]
