# Generated by Django 5.2 on 2026-09-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0008_alter_user_chave_publica_maquina_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='chave_publica_maquina',
            new_name='machine_public_key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usuario_maquina',
            new_name='machine_user',
        ),
    ]
