# Generated by Django 5.2 on 2026-09-27 15:26

import Domain.models.proxies.election.votingTokenProxy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0009_rename_chave_publica_maquina_user_machine_public_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was first created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last modified.', verbose_name='Updated At')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the raw token. The raw value is never stored.', max_length=64, unique=True, verbose_name='token hash')),
                ('is_used', models.BooleanField(default=False, help_text='True after the token has been consumed to cast a vote.', verbose_name='is used')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when the token was consumed.', null=True, verbose_name='used at')),
                ('used_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which the token was consumed (forensic log).', null=True, verbose_name='used from IP')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_tokens', to='Domain.election', verbose_name='election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_tokens', to='Domain.electoralcollege', verbose_name='voter')),
            ],
            options={
                'verbose_name': 'Voting Token',
                'verbose_name_plural': 'Voting Tokens',
                'ordering': ['-created_at'],
            },
            bases=(Domain.models.proxies.election.votingTokenProxy.VotingTokenProxy, models.Model),
        ),
    ]
