# Generated by Django 5.2 on 2026-09-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0010_voting_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoralcollege',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Indicates whether the voting email has been sent to this voter', verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='electoralcollege',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last email sent to this voter', null=True, verbose_name='email sent at'),
        ),
    ]
